# image : docker-registry.esrf.fr/bcu/lima-ci-debian8:latest
#before_script :

stages:
  - build
  - test

build :
  stage: build
  script:
    - ./install.sh python test
    - ls -l
  artifacts:
    paths:
    - cmake-build/
  only:
    - cmake


test :
  stage: test
  dependencies:
    - build
  script:
    - cd cmake-build/
    - ctest --timeout 10
    - cd ../..
    - pwd
    - cd
    - pwd
  only:
    - cmake
