# image : docker-registry.esrf.fr/bcu/lima-ci-debian8:latest
#before_script :

stages:
  - build
  - test

build :
  stage: build
  script:
    - git submodule init third-party/Processlib
    - git submodule update
    - cd third-party/Processlib
    - git remote add gitlab git@gitlab.esrf.fr:limagroup/processlib.git
    - git fetch gitlab
    - git checkout gitlab/cmake
    - cd ../..
    - ./install.sh tests python 
    - ls -l
  artifacts:
    paths:
    - build/
  only:
    - cmake


test :
  stage: test
  dependencies:
    - build
  script:
    - cd build/
    - ctest --timeout 10
  only:
    - cmake
