sudo: required

language: cpp

git:
  submodules: false

services:
  - docker
  
before_install:
  - docker pull esrfbliss/lima-ci-debian8
  - docker run -it esrfbliss/lima-ci-debian8 /bin/bash -c "cd /root; ./install_lima_submodule; cd lima/; ./install.sh python tests"
  
script:
  - docker exec esrfbliss/lima-ci-debian8 /bin/bash "cd /root/lima/cmake-build/ && ctest"


branches:
  only:
  - cmake  
