sudo: required

language: cpp

git:
  submodules: false

services:
  - docker
  
before_install:
  - docker pull esrfbliss/lima-ci-debian8
  - docker run -it esrfbliss/lima-ci-debian8 /bin/bash 
  
script:
  - docker exec esrfbliss/lima-ci-debian8 /bin/bash "cd /root && ./install_lima_submodule"
  - docker exec esrfbliss/lima-ci-debian8 /bin/bash "cd /root/Lima/ && ./install.sh python tests"
  - docker exec esrfbliss/lima-ci-debian8 /bin/bash "cd /root/Lima/cmake-build/ && ctest --timeout 10"
  
branches:
  only:
  - cmake  
