sudo: required

language: cpp

git:
  submodules: false

services:
  - docker
  
before_install:
  - docker pull esrfbliss/lima-ci-debian8
  - docker run -it esrfbliss/lima-ci-debian8 /bin/bash 
  
script:
  - cd /root && ./install_lima_submodule
  - Lima/ && ./install.sh python tests
  - cmake-build/ && ctest --timeout 10
  
branches:
  only:
  - cmake  
